### ISSUE TITLE
Uninitialized constant VagrantPlugins::DNS::Action::RegisterPatterns::YAML (NameError)

### ISSUE THREAD

**Issue by lox** [he9lin/vagrant-dns#2]
I'm getting the following error under Vagrant 1.3.1:

```
 ~/Projects/99designs/vmconfig/ on master ∆ › vagrant provision
[dns] Created resolvers for tlds ["vm"]
[dns] Existed daemons dir /Users/lachlan/.vagrant.d/tmp/dns/daemon
/Users/lachlan/.vagrant.d/gems/gems/lh-vagrant-dns-0.0.6/lib/vagrant-dns/action/register_patterns.rb:17:in `call': uninitialized constant VagrantPlugins::DNS::Action::RegisterPatterns::YAML (NameError)
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.0/lib/vagrant/action/warden.rb:34:in `call'
    from /Users/lachlan/.vagrant.d/gems/gems/lh-vagrant-dns-0.0.6/lib/vagrant-dns/action/create_daemons_dir.rb:23:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.0/lib/vagrant/action/warden.rb:34:in `call'
    from /Users/lachlan/.vagrant.d/gems/gems/lh-vagrant-dns-0.0.6/lib/vagrant-dns/action/create_resolvers.rb:31:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.0/lib/vagrant/action/warden.rb:34:in `call'
    from /Users/lachlan/.vagrant.d/gems/gems/lh-vagrant-dns-0.0.6/lib/vagrant-dns/action/setup_env.rb:21:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.0/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.0/lib/vagrant/action/builtin/env_set.rb:19:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.0/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.0/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.0/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.0/lib/vagrant/action/builder.rb:116:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.0/lib/vagrant/action/runner.rb:61:in `block in run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.0/lib/vagrant/util/busy.rb:19:in `busy'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.0/lib/vagrant/action/runner.rb:61:in `run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.0/lib/vagrant/machine.rb:147:in `action'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.0/plugins/commands/provision/command.rb:26:in `block in execute'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.0/lib/vagrant/plugin/v2/command.rb:182:in `block in with_target_vms'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.0/lib/vagrant/plugin/v2/command.rb:180:in `each'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.0/lib/vagrant/plugin/v2/command.rb:180:in `with_target_vms'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.0/plugins/commands/provision/command.rb:25:in `execute'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.0/lib/vagrant/cli.rb:38:in `execute'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.0/lib/vagrant/environment.rb:485:in `cli'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.0/bin/vagrant:96:in `<top (required)>'
    from /Applications/Vagrant/bin/../embedded/gems/bin/vagrant:23:in `load'
    from /Applications/Vagrant/bin/../embedded/gems/bin/vagrant:23:in `<main>'
✗ exit 1

```

**Comment by he9lin** [comment]
Hi, I think the current version of this gem is not compatible with vagrant-1.3.0.  I'll need to look into it more.

**Comment by lox** [comment]
For what it's worth, after adding `require 'yaml'` up the top solved the problem and it seems to work fine with vagrant-1.2.x+.

**Comment by he9lin** [comment]
Thanks.
